
server:
  port: 5173

#config
spring:
  #info config
  datasource:
    #encrypt: turn on encryption -> ssl
    url: jdbc:sqlserver://localhost:1433;databaseName=<database-name>;encrypt=false
    username: sa
    password: 0520
    #driver-class-name: connect to
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  #config Spring Data Jpa Object-Relational Mapping (ORM) mapping Java classes to database tables
  jpa:
    hibernate:
      ddl-auto: update
      #console_log - debug_hibernate-run
      show-sql: true
      #
      database-platform: org.hibernate.dialect.SQLServerDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: <client-id>
            client-secret: <client-secret>
            redirect-uri: <redirect-uri>
