server:
  port: 8080

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=stickyrice;encrypt=false
    username: sa
    password: 0520
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update  # Có thể là "none", "update", "create", "create-drop"
    show-sql: true       # In SQL ra console
    database-platform: org.hibernate.dialect.SQLServerDialect

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: your-client-id
#            client-secret: your-client-secret
            # redirect-uri mặc định: "{baseUrl}/login/oauth2/code/{registrationId}"
            # Nếu bạn muốn custom thì thêm dòng này:

